# Changes here will be overwritten by Copier
_commit: 21ef16f
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: true
copyright_year: '2024'
documentation: true
email: nick@koston.org
full_name: J. Nick Koston
github_username: bluetooth-devices
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: convertertools
project_name: convertertools
project_short_description: Tools for converting python data types
project_slug: convertertools
run_poetry_install: true
setup_github: true
setup_pre_commit: true

